AziendaEdile/Models/Dipendenti.cs
namespace AziendaEdile.Models
{
    public class Dipendenti
    {
        public int IdDipendente { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Indirizzo { get; set; }
        public string CodiceFiscale { get; set; }
        public bool Coniugato { get; set; }
        public int NumFigli { get; set; }
        public string Mansione { get; set; }
    }
}

AziendaEdile/Models/Pagamenti.cs
namespace AziendaEdile.Models
{
    public class Pagamenti
    {
        public int Id { get; set; }

        public DateOnly Periodo { get; set; }

        public decimal Ammontare { get; set; }

        public bool Tipo {  get; set; }

    }
}

AziendaEdile/Models/StaticDB.cs
namespace AziendaEdile.Models
{
    public static class StaticDB
    {
        private static int _maxId = 3;
        private static List<Dipendenti> _dipendenti = [
            new Dipendenti() { IdDipendente = 1, Nome = "Francesco", Cognome = "Cannizzo", Indirizzo = "Via Dionisio 5", CodiceFiscale = "ABCDEFG123456789", Coniugato = false, NumFigli = 0, Mansione = "Studente" },
            new Dipendenti() { IdDipendente = 2, Nome = "Fr", Cognome = "Cannizzo", Indirizzo = "Via Dionisio 5", CodiceFiscale = "ABCDEFG123456789", Coniugato = false, NumFigli = 0, Mansione = "Studente" },
            new Dipendenti() { IdDipendente = 3, Nome = "Franc", Cognome = "Cannizzo", Indirizzo = "Via Dionisio 5", CodiceFiscale = "ABCDEFG123456789", Coniugato = false, NumFigli = 0, Mansione = "Studente" }
            ];

        public static List<Dipendenti> GetAll()
        {
            return _dipendenti;
        }

        public static Dipendenti? GetById(int id)
        {
            for (int i = 0; i < _dipendenti.Count; i++)
            {
                Dipendenti dipendente = _dipendenti[i];
                if (_dipendenti[i].IdDipendente == id)
                {
                    return dipendente;
                }
            }

            return null;
        }

        public static Dipendenti Add(string Nome, string Cognome, string Indirizzo, string CodiceFiscale, bool Coniugato, int NumFigli, string Mansione)
        {
            _maxId++;
            var dipendente = new Dipendenti() { IdDipendente = _maxId, Nome = Nome, Cognome = Cognome, Indirizzo = Indirizzo, CodiceFiscale = CodiceFiscale, Coniugato = Coniugato, NumFigli = NumFigli, Mansione = Mansione};
            _dipendenti.Add(dipendente);
            return dipendente;
        }
    }
}

AziendaEdile/Controllers/DipendenteController.cs
using AziendaEdile.Models;
using Microsoft.AspNetCore.Mvc;

namespace AziendaEdile.Controllers
{
    public class DipendenteController : Controller
    {
        public IActionResult Index()
        {
            return View(StaticDB.GetAll());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(string Nome, string Cognome, string Indirizzo, string CodiceFiscale, bool Coniugato, int NumFigli, string Mansione)
        {
            var dipendente = StaticDB.Add(Nome, Cognome, Indirizzo, CodiceFiscale, Coniugato, NumFigli, Mansione);
            return RedirectToAction("Index");
        }
    }
}

AziendaEdile/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AziendaEdile.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AziendaEdile/Controllers/PagamentiController.cs
using Microsoft.AspNetCore.Mvc;

namespace AziendaEdile.Controllers
{
    public class PagamentiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }
    }
}

AziendaEdile/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace AziendaEdile.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AziendaEdile/Views/Dipendente/Add.cshtml
<div class="container">
    <form asp-controller="Dipendente" asp-action="Add" method="post">
        Nome: <input class="form-control" type="text" name="Nome" />
        Cognome: <input class="form-control" type="text" name="Cognome" />
        Indirizzo: <input class="form-control" type="text" name="Indirizzo" />
        Codice Fiscale: <input class="form-control" type="text" name="CodiceFiscale" />
        <br />
        Coniugato? <input class="form-check-label" type="checkbox" name="Coniugato" value="1" />
        <br />
        <br />
        Numero Figli: <input class="form-control" type="number" name="NumFigli" />
        Mansione: <input class="form-control" type="text" name="Mansione" />
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

AziendaEdile/Views/Dipendente/Index.cshtml
@section styles {
    <link href="c:\users\fcann\documents\epicode\corsofullstack\esercitazioni\backend\settimana 4 asp.net mvc\s1l1\aziendaedile\aziendaedile\styles\stylesheet.css" rel="stylesheet" />
}

<div class="container mt-4">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">Cognome</th>
                <th scope="col">Indirizzo</th>
                <th scope="col">Codice Fiscale</th>
                <th scope="col">Coniugato</th>
                <th scope="col">N. Figli</th>
                <th scope="col">Mansione</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var dipendente in Model)
            {
            <tr>
                <th scope="row">@dipendente.IdDipendente</th>
                <td>@dipendente.Nome</td>
                <td>@dipendente.Cognome</td>
                <td>@dipendente.Indirizzo</td>
                <td>@dipendente.CodiceFiscale</td>
                <td>@(dipendente.Coniugato ? "Si" : "No")</td>
                <td>@dipendente.NumFigli</td>
                <td>@dipendente.Mansione</td>
            </tr>
            }
        </tbody>
    </table>
</div>

AziendaEdile/Views/Home/Index.cshtml
<div class="container">
    <h1>FC Edile</h1>
    <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://www.ilsapacifici.it/wp-content/uploads/2020/07/calcestruzzo_venezia-treviso_ilsa-pacifici.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://optimise2.assets-servd.host/big-nilgai/assets/comefare/2018/03/calcestruzzo-3.jpg?w=2560&h=1706&q=82&auto=format&fit=crop&fp-x=0.5&fp-y=0.5&dm=1628149056&s=b711b38d8c3b230ef729c5110f8494d0" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://i.redd.it/revub66536b51.jpg" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

AziendaEdile/Views/Pagamenti/Add.cshtml
<form>
    <input type="text" placeholder="Scrivi qui..." />
</form>

AziendaEdile/Views/Pagamenti/Index.cshtml
<div class="container mt-4">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Periodo</th>
                <th scope="col">Ammontare</th>
                <th scope="col">Tipo</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <tr>
                <th scope="row">1</th>
                <td>27/02/2024</td>
                <td>4900.00€</td>
                <td>Pagamento</td>
            </tr>
            @* da popolare *@
        </tbody>
    </table>
</div>

AziendaEdile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @RenderSection("styles", required:false)
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
</head>
<body>
    <header class="">
        <nav class="navbar navbar-expand-lg bg-secondary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">FC Edile</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/Dipendente/Index">Dipendenti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/Pagamenti/Index">Pagamenti</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    @RenderSection("scripts", required:false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>